07-inference-for-numerical-responses/03-lesson/07-03-lesson.Rmd
Large changes made are: 
- moving from `group_by()` for observed statistics to using **infer** tools 
- moving from `quantile()` for CI to `get_confidence_interval()` 
- moving from `t.test()` to `t_test()` 
Smaller changes: 
- changing hypothesis notation
- using a proportion for a p-value instead of a probability
=> revisions to numerical inference per course prep

07-inference-for-numerical-responses/02-lesson/07-02-lesson.Rmd, 07-inference-for-numerical-responses/03-lesson/07-03-lesson.Rmd, 07-inference-for-numerical-responses/04-lesson/07-04-lesson.Rmd
Similar changes to the Inference tutorial: 
- changed from `t.test()` to `t_test()` 
- use `get_p_value()` to find p-value instead of `summarize()` 
Note: the original example with overtime worked was not compatible, as that variable was not in the `gss` dataframe. This example has been changed to estimating the number of hours worked, and comparing the `acs12` confidence interval to the `gss` interval.
=> t-distribution Review

01-getting-started-with-data/03-lesson/01-03-lesson.Rmd
The command ends in the second line; the second pipe goes nowhere and generates an error.
=> delete last pipe

02-summarizing-and-visualizing-data/02-lesson/02-02-lesson.Rmd
The ex2 exercise chunk generates the error message: "object `common_cyl` not found" because the nameless chunk, where the new dataset `common_cyl` is generated, does not function as a setup chunk for exercise ex2.
=> add `common_cyl` to ex2 setup

02-summarizing-and-visualizing-data/04-lesson/02-04-lesson.Rmd
Both libraries are already loaded in the setup chunk. Reloading `openintro` destroys changes in the setup chunk to the variable `spam` from the `email` dataset. Exercises that relied on these changes did not work correctly.
=> 02-04-lesson: delete code chunk `load-pkg`

01-getting-started-with-data/04-lesson/01-04-lesson.Rmd
The name for the resulting data frame is mentioned with 'evals' in the text.
Maybe it would be better to use the name 'evals_fortified' as it leaves the original data set unchanged.
But in that case, you would need to change 
- the last two exercises (especially the last one where you are using the new variable 'cls_type') and
- the name of the resulting data frame in your setup chunk.
=> 01-04-lesson: change the name of the resulting data frame to "evals"

02-summarizing-and-visualizing-data/02-lesson/02-02-lesson.Rmd
This is not an error, just a suggestion.
1. So students could/should inspect the outcome for themselves before they got the explanation.
2. Some of the explanation is only understandable after inspecting the `glimpse()` outcomes.
--- At the end there is also a typo I have overlooked last time.
=> Move `glimpse(cars)` in front of explanation

02-summarizing-and-visualizing-data/04-lesson/02-04-lesson.Rmd
The text says that students can see 3.921 emails, but actually without the max.print option they see  only 1.000.
It is crucial for the case study that students understand what the variables mean. But there is no exercise chunk at hand where they could read the help file by typing `?email`. I propose therefore a link to the OpenIntro page for the description of the email data set.
=> set `max.print` option to 4000 & add link to data set description

02-summarizing-and-visualizing-data/04-lesson/02-04-lesson.Rmd
At the moment [you can't mix markdown and R Markdown](https://github.com/rstudio/learnr/issues/421). Therefore, the solution could not be seen by students whenever there is a div hint.
The solution to progressively reveal hints does not work well as the solution chunk is very long, and the hint windows take on the same size, even if their text is much shorter.
So my suggestion is to write the hint as regular text before the exercise chunk. I think this is justified as it is a very general hint which does not spoil the main challenges of the exercise task.
=> convert the div hint to standard text and put it before exercise chunk

01-data/01-lesson/01-01-lesson.Rmd
If you are using a markdown hint, students can't see the solution chunk. Not being able to mix markdown hints with R markdown hints or solution is annoying as markdown hints are generally supposed not to be code but provide additional thoughts students should observe.
As a workaround, I have added general hints as comments in R Markdown chunks. To prevent an overflowing line, I had the text separate into several lines. Additionally, I have added coded hints as well. Not ideal, but the only workaround I can see to mix these two kinds of clues.
****
As you can see, I have started again to revise the tutorials in the new structure for the 1st edition of the new book. I hope this is ok, if not please tell me.
=> change markdown hints to R markdown hints

01-data/01-lesson/01-01-lesson.Rmd
The URL https://openintrostat.github.io/ims-tutorials/01-getting-started-with-data/ does not work (anymore).
I noticed that there are two addresses to the same content of the tutorials.
1. One URL has the pattern
- https://openintro.shinyapps.io/ims-01-getting-started-with-data-01/
- …data-02
- …data-03 etc.
This is the URL from the final section of the tutorial (congratulation section)
2. Another URL has the pattern
- https://openintro.shinyapps.io/ims-01-data-01/
- …data-02
- …data-03 etc.
This is the (newer) URL from the tutorial description.
=> change link address

02-explore/01-lesson/02-01-lesson.Rmd
The many changes result from a different educational approach: Instead, to present text, I suggest changing the options of the R chunks from "echo=TRUE" sometimes even combined with "eval=FALSE" to "exercise=TRUE" chunks so students have to click the "Run Code" button themselves. To support the exploring approach, I had to separate some code lines into different chunks and rewrite some text passages.
This long first section of the file uses just chunks with "echo=TRUE" so students can only read. I suggest turning these chunks into "exercise=TRUE" so students can explore themselves. This different approach also requires some text changes.
I also changed the reported figures as the original comics dataset was changed with `droplevels()` in the R setup chunk. 
****
Please take this just as a …
=> turn "echo=True, eval=FALSE" chunks to "exercise=TRUE" 

01-data/02-lesson/01-02-lesson.Rmd
As @atheobold in fix #10 had mentioned already in Sept. 2020, these two images are missing. 
If the images are not available, I would suggest deleting these two lines because the text will still be understandable; respectively, in my understanding, the text does not require these two images. (resolve #10)
=> delete references to missing images

02-explore/01-lesson/02-01-lesson.Rmd
To display the complete simplified dataset `comics_filtered` does not show the difference immediately. I suggest checking if the unused level is dropped successfully.
***
Not sure if the markdown hint about `!=` is a good idea. As it is already present in the task guidance, it is not asked for, but it destroys the step-by-step guidance of the solution.
=> check result more specifically

03-model/02-lesson/03-02-lesson.Rmd
The original plot has fig.height=3, fig.width=5, which seems too small. You cannot discern any correlation tendency. --- But I do not know if this bigger graph scales correctly for a mobile version.
=> make facet_wrap plot bigger

03-model/02-lesson/03-02-lesson.Rmd
Just "Incorrect" as (automatic) feedback is confusing: When looking for a **wrong** statement, "incorrect" means the distractor itself is accurate.
Although I prefer explicit feedback with all questions, I generally wrote no PRs for elaborated feedback. But I think with double negatives, the input has to be more detailed.
=> Clarify feedback for double-negative feedback

03-model/02-lesson/03-02-lesson.Rmd
Without the package name the exercise at the first [#section-your-turn](https://openintro.shinyapps.io/ims-03-introduction-to-linear-models-02/#section-your-turn) fails with the following error: 
> Problem with `summarise()` input `correlation_between_x_and_y`. ✖ 'x' must be numeric ℹ Input `correlation_between_x_and_y` is `cor(x, y)`. ℹ The error occurred in group 1: set = "".
I tracked the problem to a masking problem: In R chunks, the original dataset "anscombe" is masked (hidden) by the new global modified variable with the same name. But this is not the case in R exercise chunks. (At least that is my explication…)
Alternatively, one could generate a variable with a different name (e.g., `anscombe_mod <- anscombe`) and change all those chunks (R and exercise chunks) where it is used. …
=> For correct masking in exercise chunk refer in setup chunk to package `datasets`

03-model/01-lesson/03-01-lesson.Rmd
Tutorial #3 now has 10 lessons. Provide links to them. This has to be done for all lessons in the tutorial on regression modeling (copy & paste).
I will provide the next few days also the changes for the book to this issue.
NOTE: I could not manage the R code for the emoji of lesson 10 and have it included as an inline icon. `r emo:ji("ten")` displays a 10 o'clock watch in my installation.
NOTE: Cannot call lesson 6  because of a missing graph in a knitr::include_graphics() command. (lines 457-458). I think I have found the problem: the graphic of chunk "mpg-data-parallel" has to be saved + called. If this is correct, a PR to this issue will follow in a few days.
=> Add missing links for lessons 6-10 to TOC

03-model/06-lesson/03-06-lesson.Rmd
Calling Lesson 6 resulted into an error messages: 
> An error has occurred
> The application failed to start: exited unexpectedly with code 1
> processing file: 03-06-lesson.Rmd
> Quitting from lines 457-458 (03-06-lesson.Rmd) 
> Error in value[[3L]](cond) : 
>  Cannot find the file(s): "04-01-lesson_files/figure-html/mpg-data-parallel-1.png"
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Execution halted
The URL from `knitr::include_graphics` needed to be adapted to the new tutorial structure. (This is the first of the promised changes I mentioned in PR #84).
=> adapt link address to new tutorial structure

03-model/03-lesson/03-03-lesson.Rmd
1. Variable name for bodyweight in `bdims` is not `bwt` but `wgt`
2. Minor typos fixed in bullet point sentences 
3. Added links for lessons 6-10 in TOC
=> Several minor typos and added lessons links no 6-10

03-model/04-lesson/03-04-lesson.Rmd, 03-model/06-lesson/03-06-lesson.Rmd
In the original version, students get by choosing the options 1, 2, or 3 the feedback "Incorrect". But the selection itself is correct; even it is only partly correct.
Besides, I had to delete "None of the above" because the correct answer "All of the above" IS above this last option.
[Technically, one would formulate this question as a Multiple-Choice question (symbolized with checkboxes instead of radio boxes). But of design errors in the `learnr` package, you cannot provide correct feedback for all options AND allow for retrying the question. (I plan to report this problem in the question design to RStudio.)
(Sorry for the second file change. I do not know why this appeared here. We have already corrected this wrong link address and merged it successfully. --- I do not know how to …
=> Change feedback of wrong answers.

03-model/04-lesson/03-04-lesson.Rmd
Using a double negative question is always confusing. The second option is judged as correct in the original question, e.g., this assertion should be **incorrect**. But it is actually correct.
On the other hand, the last option, "None of the above" questions are incorrect, is actually the correct one.
To prevent misunderstandings, I have explained the reasoning explicitly for all options.
=> Change the question chunk mc3

03-model/04-lesson/03-04-lesson.Rmd
1. I'm not sure if output to the 'console' is a correct expreession with learnr tutorials.
2. The name of the linear model is `hgt_wgt_mod` and not `mod`
This closes #96.
3. In chunk ex7 convert markdown hint to R Markdown hint comment as the first prevents the display of the solution.
=> Fix Typo and convert markdown hint to R Markdown hint

02-explore/03-lesson/02-03-lesson.Rmd
These calculations should recalculate the mean rather than using the result from life_ma_summary, as that result is rounded. Otherwise the second result doesn't match the result from var!
=> calculate variance using exact mean rather than rounded

02-explore/02-lesson/02-02-lesson.Rmd
Removing this comma got rid of the error mentioned in Issue #163 .
=> issue 163 fixed

02-explore/01-lesson/02-01-lesson.Rmd
"The pipe operator requires a function call as RHS" in chunk pie caused by using "|>count" instead of "|>count()"
in 02-01-lesson.Rmd
=> Fixed error in 02-01:

04-foundations/04-lesson/04-04-lesson.Rmd
I have defined the one_poll, one_poll_boot and p_hat objects in the lesson setup so that they can be accessed when needed in the various exercises.
The tutorial claims that "one_poll, ... one_poll_boot,... and p_hat are available in your workspace". However, they are not available in the workspace and it causes many errors. For example, exercises bootstrap_percentile_2 and bootstrap_percentile_3 throw an error because "object 'one_poll_boot' not found".
As a side note: the one_poll_boot object is created at least 7 times in this lesson, likely as partial patches to the object not being defined in the initial lesson setup.
=> Bugfix for 04/04. Needed objects defined in the lesson setup. 

01-data/01-lesson/01-01-lesson.Rmd
Tutorial 01-01: changed use of learnrhash::encoder_logic to the one defined in the in the R folder. It now matches the other tutorials.
=> Tutorial 01-01: hash generation is inconsistent with all other tutorials. 

04-foundations/03-lesson/04-03-lesson.Rmd
following from closed issue #115  there's still a discrepancy between the `summarizing_opportunity_cost-solution` p-values and the ones reported in the `opportunity_cost_conclusion` and `mc1` chunks. it appears to be due to the exercise-specific definition of `opp_perm` which has a p-value of 0.017 whereas the initial `setup` chunk definition of `opp_perm` has the calculated p-value of 0.007.
=> potential solution to p-value discrepancy (tutorial 4.3)

04-foundations/02-lesson/04-02-lesson.Rmd, 04-foundations/03-lesson/04-03-lesson.Rmd, 04-foundations/04-lesson/04-04-lesson.Rmd
updates that could resolve open issue #261
=> suggested edits due to infer package 1.0.0 update

05-infer/07-lesson/05-07-lesson.Rmd
This PR addresses issue #243 by making the hrly_pay variable accessible in exercise 5 of tutorial 7.
The setup chunk that creates acs12_complete_hrlypay_citizen and hrly_pay had include = FALSE, which meant these objects were not accessible in the exercise chunk. This was causing 'object not found' errors when students tried to complete the exercise.
Changes made:
- Removed include = FALSE from the citizens_5-setup chunk in 05-infer/07-lesson/05-07-lesson.Rmd to make the objects available in the exercise
Fixes #243
=> fix: make hrly_pay accessible in exercise 5

03-model/09-lesson/03-09-lesson.Rmd
This PR addresses issue #268 by making objects accessible in exercise 5 of tutorial 9.
The setup chunk containing 'mod' and 'gpa_bins' objects was previously unnamed, which meant these objects were not available in the exercise chunk, causing 'object not found' errors. Adding the name 'ex5-setup' makes these objects accessible in the exercise.
Changes made:
- Added chunk name 'ex5-setup' to the setup chunk in tutorial 9 (03-model/09-lesson/03-09-lesson.Rmd) to make objects available in exercise 5
Fixes #268
=> fix: make objects accessible in exercise 5 by adding setup chunk name

05-infer/05-lesson/05-05-lesson.Rmd
This PR addresses issue #253 where the 'object not found' error occurs because ncbirths_complete_visits was being created in individual exercise chunks.
In learnr tutorials, objects created in one exercise are not available in subsequent exercises. This PR moves the object creation to the data prep section to ensure it's available globally throughout the tutorial.
The change is minimal - we're just adding a comment to document the existing code in the data prep section, as the object was already being created there.
Fixes #253
=> fix: move ncbirths_complete_visits to data prep section
