OpenIntroStat/ims-tutorials

- 01-getting-started-with-data/01-lesson/01-01-lesson.Rmd
The majority of my revisions are focused on making the tutorial more beginner friendly. When making changes I thought of the hurdles my students often face when learning `R`, so some explanations may be overly simple for some students.
> Revisions to Starting with Data Tutorial 

- 01-getting-started-with-data/01-lesson/01-01-lesson.Rmd
- 01-getting-started-with-data/02-lesson/01-02-lesson.Rmd
The changes to this episode primarily consist of (1) adding an explanation/exploration of `group_by()`, (2) adding a note on gender inclusive language in surveys, and (3) adding hints to the longer data wrangling tasks.
Fingers crossed my old commits that are showing up in this PR go away. If not, I apologize for any headaches this causes!
> Review of Episode 02 in Lesson 01

- 05-introduction-to-statistical-inference/01-lesson/05-01-lesson.Rmd
- 05-introduction-to-statistical-inference/02-lesson/05-02-lesson.Rmd
- 05-introduction-to-statistical-inference/04-lesson/05-04-lesson.Rmd
My main changes are as follows: 
- additional descriptions of what the code is doing
- adding step by step directions of what to do in longer code chunks
- fixed SE calculation with NA
- changed figure alignment so text boxes aren't being cut off
- removing pull() from code since it's not necessary and will confuse students
- changed hints that are only text
> changes to tutorials per class prep

- 01-getting-started-with-data/01-lesson/01-01-lesson.Rmd
- 01-getting-started-with-data/02-lesson/01-02-lesson.Rmd
- 01-getting-started-with-data/03-lesson/01-03-lesson.Rmd
Silly me, I added the `read_cat` variable to the data in the set-up chunk!
> minor data error in setup

- 01-getting-started-with-data/01-lesson/01-01-lesson.Rmd
- 02-summarizing-and-visualizing-data/03-lesson/02-03-lesson.Rmd
Additions to syntax walk throughs, more hints, cleaner plot output, included `if_else()` function, removed repetitive exercises
> 02-03 Revisions

- 03-introduction-to-linear-models/01-lesson/03-01-lesson.Rmd
- 03-introduction-to-linear-models/02-lesson/03-02-lesson.Rmd
I did add jittering on top of boxplots!
> minor changes, mainly adding structure to exercises and outputting code

- 01-getting-started-with-data/index.Rmd
`sample_n()` is deprecated, and correctly not used in the tutorial.
> Replace `sample_n()` with `slice_sample()`

- 02-summarizing-and-visualizing-data/02-lesson/02-02-lesson.Rmd
You refer to the code "The code below…" so you need `echo = TRUE`.
BTW: Two other code chunks are missing, but they do have `echo = TRUE` in their chunk header. Perhaps an older compilation? - I am referring to the R chunks 'dotplot-cars' and 'hist' in this file. Their code is not included in the current version.
> 02-02-lesson: add code chunk(s)

- 02-summarizing-and-visualizing-data/02-lesson/02-02-lesson.Rmd
- 02-summarizing-and-visualizing-data/04-lesson/02-04-lesson.Rmd
Sorry, I mistakenly pulled these small changes with another file. I reverted my original commit and started this from scratch. I will write PRs for the other – more complicated changes – separately.
> 02-02-lesson: fix some typos

- 03-introduction-to-linear-models/01-lesson/03-01-lesson.Rmd
The second chunk did not have a name, so I added one. Feel free to change the name.
> add 'echo = TRUE' to 2 missing code chunks

- 03-introduction-to-linear-models/01-lesson/03-01-lesson.Rmd
In the solution chunk `ex2-solution` the x variable `weeks_cut` is missing.
> add `weeks_cut` as variable

- 02-summarizing-and-visualizing-data/01-lesson/02-01-lesson.Rmd
There is a third closing parenthesis correctly in the solution. But this third closing parenthesis is missing in the exercise and in two of the hints.
> add third closing parenthesis

- 02-summarizing-and-visualizing-data/01-lesson/02-01-lesson.Rmd
In setup and exercise, `comics_updated` is used correctly, but the solution shows `comics`.
> replace `comics` with `comics_updated`

- 02-summarizing-and-visualizing-data/01-lesson/02-01-lesson.Rmd
(a) The `+` in the last line of the exercise with `ggplot` has to be deleted.
(b) hint & solution are the same/redundant and
(c) solution uses wrongly `pies` instead of `pies_updated`
> delete redundant hint and last `+`

- 02-summarizing-and-visualizing-data/03-lesson/02-03-lesson.Rmd
The name of the population variable is not `var` but `pop`.
> enter correct name of population variable

- 02-summarizing-and-visualizing-data/03-lesson/02-03-lesson.Rmd
The dataset **was** saved to a new object in the previous r chunk.
> replace "didn't save" with "saved"

- 02-summarizing-and-visualizing-data/02-lesson/02-02-lesson.Rmd
> change several col_types from `dbl` to `int`

- 02-summarizing-and-visualizing-data/04-lesson/02-04-lesson.Rmd
The text mentions it but it is not done in the code, so the bar chart remains black/white.
> use `fill = zero` to color the bar chart

- 01-data/01-lesson/01-01-lesson.Rmd
Additionally I have also deleted 'Next' as it already mentioned in the last line of the previous section.
> Add missing level 3 header

- 01-data/01-lesson/01-01-lesson.Rmd
wrap the assignment code in parentheses so student can see the effect of the `mutate()` command.
> display data frame with new generated variable

- 02-explore/01-lesson/02-01-lesson.Rmd
Students who are not sure and just try will get no reasoning. Besides: An additional explanation is always good and reinforces learning.
> add reason to correct answer

- 02-explore/01-lesson/02-01-lesson.Rmd
Also: Mark hint advice as comment and repeat it for the solution.
> `mutate()` as adding a variable instead of changing

- 03-model/02-lesson/03-02-lesson.Rmd
I have linked with 'target=_blank' to prevent overwriting the actual shiny web page.
> 2 typos & 2 links

- 03-model/04-lesson/03-04-lesson.Rmd
The first scatterplot shows the newly created variable `course_number`. To understand was what going on in the previous `glimpse()` chunk 1 the student should already see the `course_number` variable. Otherwise, students would not understand what happened. Therefore I suggest transferring the chunk with the mutate-conversion before the glimpse chunk.
> show data set 'textbook' with new `course_number` variable

- 03-model/04-lesson/03-04-lesson.Rmd
1. The name of the dataset is `mlbbat10` and not `mlbBat10`
2. Instead of uppercase letters for the variable I think 'slg'/'opb' is more helpful
3. I integrated the markdown div-hint as a R Markdown comment. Otherwise the solution is not displayed
4. I separated the full solution into different steps of hints
5. In ex2 the hint was erroneously named ex1
> Restructure first fitting exercise

- 03-model/05-lesson/03-05-lesson.Rmd
In the previous version, there were only 5 tutorials lessons. Now there are 10. Therefore I changed 'completed" to 'half completed' and adapted the text accordingly.
> Adapt to new lesson structure

- 03-model/05-lesson/03-05-lesson.Rmd
It is not clear which variable to use for the last exercise (chunk ex8). It says, "Create a visualization of the relationship between at bats and obp…" but then all the following commands and text passages refer to `slg` and `obp`.
I assume that the relationship between `at_bat` and `obp` is meant. I am not sure if this makes sense because I have no idea about baseball.
[From a cross-cultural perspective, I think that baseball is not a good example. In some parts of the world, this sport is not popular, and people (like me) even know the rules of the game and therefore cannot understand the different variables of the dataset `mlbbat10`.]
closes #92
> Correct variable names and adapt exercise

- 03-model/05-lesson/03-05-lesson.Rmd
change wrong dataframe name `bdims_augment_wgt_hgt` to `wgt_hgt_augment`
closes #94
> change name of dataframe

- 03-model/04-lesson/03-04-lesson.Rmd
1. The text says that `broom` is already loaded (and it is, via tidyverse). So skip/delete this task
2. Create `hgt_wgt_tidy` (not `bdims_tidy`)
> Adapt chunk ex5

- 03-model/02-lesson/03-02-lesson.Rmd
- 03-model/04-lesson/03-04-lesson.Rmd
- 03-model/05-lesson/03-05-lesson.Rmd
- 03-model/06-lesson/03-06-lesson.Rmd
- 03-model/07-lesson/03-07-lesson.Rmd
- 03-model/08-lesson/03-08-lesson.Rmd
- 03-model/09-lesson/03-09-lesson.Rmd
- 03-model/10-lesson/03-10-lesson.Rmd
1) files 03-02, 03-04 & 03-05: add lessons 06-10
2) files 03-06 - 03-10: add missing lessons 01-05 and change in TOC lesson 4 to lesson 3.
> Add missing lessons to TOC

- 03-model/06-lesson/03-06-lesson.Rmd
The URLs to this lesson still generate errors. But they are correct ("ims-03-model-06/"). I have also changed the internal URLs in this file to the new structure in a previous PR. To check if everything is correct, you would need to upload the new version to shinyapps.io. 
I have collected all six commits into one PR. Please tell me if this is ok or if you would prefer "one change / one commit = one PR).
> 03-06 Lesson: Several adaptions and fixing some typos

- 01-data/01-lesson/01-01-lesson.Rmd
As I had open all the necessary files, I did this correction. Hopefully, this is in your sense?
close #122
> Correct sentence

- 02-explore/02-lesson/02-02-lesson.Rmd
It is a bit odd to have ex2-setup as an exercise when it doesn't display any output. This commit makes a new chunk for display and a copy of it for setup. Improving fix #152. 
This is an alternative approach to #156 to avoid re-opening issue #152.
> Improving fix #152. Making ex2-setup in tutorial 02-02.

- 03-model/02-lesson/03-02-lesson.Rmd
Hi Mine, 
From a learning perspective I understand the problem brought up in the issue (#86); we're asking students to make a plot and guess the correlation but they don't see the plot until they write the code to calculate the correlation. 
I split the exercises into parts a and b and changed labels accordingly. I'm not sure if there are any references to these exercises elsewhere that would need to be adjusted as well. 
Since this is more of a structural change to the tutorials, I'll leave it to you and the other authors to decide if this should be merged. 
Best, 
~N
> adjustments for issue #86

- 03-model/02-lesson/03-02-lesson.Rmd
Fix for issue #176 (broken image link)
> broken image link fixed

- 02-explore/04-lesson/02-04-lesson.Rmd
Fixed #171 by adding "echo=TRUE" to code chunks that were seemingly meant to be displayed.
Fixed typo in the comparison of pie charts and bar charts.
> Fixed #171 by adding "echo=TRUE" to code chunks

- 03-model/07-lesson/03-07-lesson.Rmd
Both caused by missing exercise setups.
Fixed #183. Fixed #184.
> Bug fix for #183 and #184.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Pulled the templates from the openintro repo and edited text to fit this repo.
> added issue templates

- 06-model-infer/02-lesson/06-02-lesson.Rmd
- 06-model-infer/03-lesson/06-03-lesson.Rmd
- 06-model-infer/05-lesson/06-05-lesson.Rmd
Various bug fixes across tutorial 06 (lessons 01 and 04 were completed in a separate branch). 
Most fixes are related to data not being accessible to exercises or multiple choice questions not being implemented properly.
> Bug/tutorial06 lessons02,03,05

- 06-model-infer/04-lesson/06-04-lesson.Rmd
Mostly to do with needed datasets not being accessible within the exercises.
> Various fixes for Tutorial 06 lesson 04.

- 06-model-infer/02-lesson/06-02-lesson.Rmd
I deleted exercise ex27 (I changed it to the multiple choice question that was intended), but I failed to delete its hint or solution chunks, which caused an error.
> Fixing a bug I introduced into Tutorial 6 lesson 02. 

- 05-infer/05-lesson/05-05-lesson.Rmd
The data set causing the error was only included in the setup for exercise 4 so exercise 5 couldn't see it. Instead of duplicating the exercise-setup code chunk I moved it to the main setup chunk.
> moved exercise prep to setup chunk

- 05-infer/05-lesson/05-05-lesson.Rmd
- 05-infer/06-lesson/05-06-lesson.Rmd
- 05-infer/07-lesson/05-07-lesson.Rmd
Fixes typos related to issues 245-252 & 254.
> Typo fixes for multiple issues

- 05-infer/01-lesson/05-01-lesson.Rmd
- 05-infer/02-lesson/05-02-lesson.Rmd
- 05-infer/03-lesson/05-03-lesson.Rmd
- 05-infer/04-lesson/05-04-lesson.Rmd
- 05-infer/05-lesson/05-05-lesson.Rmd
- 05-infer/06-lesson/05-06-lesson.Rmd
- 05-infer/07-lesson/05-07-lesson.Rmd
- 05-infer/08-lesson/05-08-lesson.Rmd
You may not want all of these edits so I separated them out into two different commits and only made stylistic changes to keep things consistent with the style of the previous tutorials. Keep what you want and leave the rest :)
> typos, formatting, rewording for clarification (tutorial 5)
